"""Tests for src/preprocessing/pipeline.py — PreprocessingPipeline.

Unit tests mock the OCR extractor and CV pipeline so no external services
or OpenCV are required.  The integration test at the bottom exercises the
full pipeline with a mocked OCR extractor against the synthetic fixture image
generated by conftest.py.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from PIL import Image

from src.models import BoundingBox, CVResult, DiagramMetadata, TextLabel
from src.preprocessing.cv_pipeline import CVPipeline
from src.preprocessing.ocr import DocumentAIOCRExtractor
from src.preprocessing.pipeline import PreprocessingPipeline, _detect_format

# ---------------------------------------------------------------------------
# Test helpers / stubs
# ---------------------------------------------------------------------------


class _StubCV:
    """CV pipeline stub — returns an empty CVResult without importing OpenCV."""

    def run(self, image: Image.Image, text_labels: object = None) -> CVResult:  # noqa: ARG002
        return CVResult()


def _make_label(
    text: str,
    cx: float = 0.75,
    cy: float = 0.85,
) -> TextLabel:
    """Create a TextLabel centred at (cx, cy) with a small bounding box."""
    hw, hh = 0.05, 0.02
    return TextLabel(
        text=text,
        bbox=BoundingBox(
            x_min=max(0.01, cx - hw),
            y_min=max(0.01, cy - hh),
            x_max=min(0.99, cx + hw),
            y_max=min(0.99, cy + hh),
        ),
        confidence=0.95,
    )


def _mock_extractor(labels: list[TextLabel] | None = None) -> DocumentAIOCRExtractor:
    """Return a DocumentAIOCRExtractor mock that resolves to *labels*."""
    extractor = MagicMock(spec=DocumentAIOCRExtractor)
    extractor.extract = AsyncMock(return_value=labels or [])
    return extractor


def _make_pipeline(
    labels: list[TextLabel] | None = None,
    cv: object | None = None,
) -> PreprocessingPipeline:
    return PreprocessingPipeline(
        ocr_extractor=_mock_extractor(labels),
        cv_pipeline=cv or _StubCV(),  # type: ignore[arg-type]
    )


def _white_image(w: int = 800, h: int = 600) -> Image.Image:
    return Image.new("RGB", (w, h), color="white")


# ---------------------------------------------------------------------------
# Tests: _detect_format helper
# ---------------------------------------------------------------------------


def test_detect_format_png_path() -> None:
    assert _detect_format(Path("drawing.png")) == "png"


def test_detect_format_tiff_path() -> None:
    assert _detect_format(Path("drawing.tiff")) == "tiff"


def test_detect_format_tif_alias() -> None:
    assert _detect_format(Path("drawing.tif")) == "tiff"


def test_detect_format_pdf() -> None:
    assert _detect_format(Path("drawing.pdf")) == "pdf"


def test_detect_format_dwg() -> None:
    assert _detect_format(Path("drawing.dwg")) == "dwg"


def test_detect_format_dxf() -> None:
    assert _detect_format(Path("drawing.dxf")) == "dxf"


def test_detect_format_unknown_extension_defaults_to_png() -> None:
    assert _detect_format(Path("drawing.svg")) == "png"


def test_detect_format_pil_image_defaults_to_png() -> None:
    """A PIL Image with no format attribute returns 'png'."""
    assert _detect_format(_white_image()) == "png"


# ---------------------------------------------------------------------------
# Tests: PreprocessingPipeline.run — return type and basic fields
# ---------------------------------------------------------------------------


async def test_run_returns_diagram_metadata() -> None:
    """run() always returns a DiagramMetadata instance."""
    pipeline = _make_pipeline()
    result = await pipeline.run(_white_image())
    assert isinstance(result, DiagramMetadata)


async def test_run_image_dimensions_from_pil() -> None:
    """width_px / height_px match the supplied PIL image dimensions."""
    pipeline = _make_pipeline()
    result = await pipeline.run(_white_image(1024, 768))
    assert result.width_px == 1024
    assert result.height_px == 768


async def test_run_format_from_pil_defaults_to_png() -> None:
    """A PIL Image with no format tag produces format='png'."""
    pipeline = _make_pipeline()
    result = await pipeline.run(_white_image())
    assert result.format == "png"


async def test_run_source_filename_pil() -> None:
    """A PIL Image source is recorded as '<PIL Image>'."""
    pipeline = _make_pipeline()
    result = await pipeline.run(_white_image())
    assert result.source_filename == "<PIL Image>"


async def test_run_accepts_path_input(sample_electrical_image: Path) -> None:
    """Pipeline accepts a filesystem Path as well as a PIL Image."""
    pipeline = _make_pipeline()
    result = await pipeline.run(sample_electrical_image)
    assert result.source_filename == "sample_electrical.png"
    assert result.format == "png"


async def test_run_image_dimensions_from_path(sample_electrical_image: Path) -> None:
    """Dimensions are read correctly when a Path is supplied."""
    pipeline = _make_pipeline()
    result = await pipeline.run(sample_electrical_image)
    assert result.width_px == 800
    assert result.height_px == 600


# ---------------------------------------------------------------------------
# Tests: text labels
# ---------------------------------------------------------------------------


async def test_run_text_labels_propagated_from_ocr() -> None:
    """Labels returned by the OCR extractor appear in the metadata."""
    labels = [_make_label("R1", cx=0.2, cy=0.3), _make_label("R2", cx=0.6, cy=0.3)]
    pipeline = _make_pipeline(labels=labels)
    result = await pipeline.run(_white_image())
    assert len(result.text_labels) == 2
    assert {lbl.text for lbl in result.text_labels} == {"R1", "R2"}


async def test_run_no_labels_gives_empty_list() -> None:
    """Empty OCR output produces an empty text_labels list."""
    pipeline = _make_pipeline(labels=[])
    result = await pipeline.run(_white_image())
    assert result.text_labels == []


# ---------------------------------------------------------------------------
# Tests: title block
# ---------------------------------------------------------------------------


async def test_run_title_block_is_populated() -> None:
    """Title block fields are extracted from in-region OCR labels."""
    labels = [
        _make_label("DWG: SCHM-001", cx=0.70, cy=0.82),
        _make_label("REV: B", cx=0.88, cy=0.82),
        _make_label("1:50", cx=0.70, cy=0.88),
    ]
    pipeline = _make_pipeline(labels=labels)
    result = await pipeline.run(_white_image())

    assert result.title_block is not None
    assert result.title_block.drawing_id == "SCHM-001"
    assert result.title_block.revision == "B"
    assert result.title_block.scale == "1:50"


async def test_run_title_block_none_when_no_region_labels() -> None:
    """Title block bbox is still set even with no matching labels."""
    # All labels are in the body (outside title block region)
    labels = [_make_label("R1", cx=0.1, cy=0.1)]
    pipeline = _make_pipeline(labels=labels)
    result = await pipeline.run(_white_image())
    # TitleBlockExtractor always sets a bbox; fields default to empty strings
    assert result.title_block is not None
    assert result.title_block.drawing_id == ""


# ---------------------------------------------------------------------------
# Tests: components and traces are empty (semantic stage pending)
# ---------------------------------------------------------------------------


async def test_run_components_empty() -> None:
    """components list is empty — semantic interpretation is Phase 3."""
    pipeline = _make_pipeline()
    result = await pipeline.run(_white_image())
    assert result.components == []


async def test_run_traces_empty_when_cv_returns_no_lines() -> None:
    """traces list is empty when the CV pipeline detects no line segments.

    _build_traces() short-circuits to [] when either components or detected_lines
    is empty, so a stub CV that returns an empty CVResult still produces no traces.
    """
    pipeline = _make_pipeline()
    result = await pipeline.run(_white_image())
    assert result.traces == []


# ---------------------------------------------------------------------------
# Tests: OCR and CV are both invoked
# ---------------------------------------------------------------------------


async def test_run_calls_ocr_extractor() -> None:
    """The OCR extractor's extract() method is called exactly once."""
    extractor = _mock_extractor()
    pipeline = PreprocessingPipeline(ocr_extractor=extractor, cv_pipeline=_StubCV())  # type: ignore[arg-type]
    await pipeline.run(_white_image())
    extractor.extract.assert_called_once()


async def test_run_calls_cv_pipeline() -> None:
    """The CV pipeline's run() method is called exactly once."""
    cv = MagicMock(spec=_StubCV)
    cv.run = MagicMock(return_value=CVResult())
    pipeline = PreprocessingPipeline(
        ocr_extractor=_mock_extractor(),
        cv_pipeline=cv,  # type: ignore[arg-type]
    )
    await pipeline.run(_white_image())
    cv.run.assert_called_once()


# ---------------------------------------------------------------------------
# Tests: error handling
# ---------------------------------------------------------------------------


async def test_run_propagates_ocr_error() -> None:
    """Exceptions from the OCR extractor are re-raised unchanged."""
    extractor = MagicMock(spec=DocumentAIOCRExtractor)
    extractor.extract = AsyncMock(side_effect=RuntimeError("API unreachable"))
    pipeline = PreprocessingPipeline(ocr_extractor=extractor, cv_pipeline=_StubCV())  # type: ignore[arg-type]

    with pytest.raises(RuntimeError, match="API unreachable"):
        await pipeline.run(_white_image())


async def test_run_continues_when_cv_returns_empty() -> None:
    """Pipeline completes normally when CV pipeline returns an empty CVResult."""

    class _EmptyCV:
        def run(self, image: Image.Image, text_labels: object = None) -> CVResult:  # noqa: ARG002
            return CVResult()

    pipeline = _make_pipeline(cv=_EmptyCV())
    result = await pipeline.run(_white_image())
    assert isinstance(result, DiagramMetadata)


# ---------------------------------------------------------------------------
# Tests: diagram_id uniqueness
# ---------------------------------------------------------------------------


async def test_run_assigns_unique_diagram_ids() -> None:
    """Each run() call produces a DiagramMetadata with a distinct diagram_id."""
    pipeline = _make_pipeline()
    r1 = await pipeline.run(_white_image())
    r2 = await pipeline.run(_white_image())
    assert r1.diagram_id != r2.diagram_id


# ---------------------------------------------------------------------------
# Integration test — uses the synthetic fixture image from conftest.py
# ---------------------------------------------------------------------------


async def test_integration_full_pipeline(sample_electrical_image: Path) -> None:
    """Full pipeline integration: synthetic image → valid DiagramMetadata.

    The OCR extractor is mocked to return labels that match what real OCR
    would produce for the conftest fixture image (DWG: TEST-001, REV: A,
    SCALE: 1:1 drawn in the bottom-right title block area).
    """
    labels = [
        # Title block labels (inside bottom-right region)
        _make_label("DWG: TEST-001", cx=0.72, cy=0.84),
        _make_label("REV: A", cx=0.88, cy=0.84),
        _make_label("SCALE: 1:1", cx=0.72, cy=0.90),
        # Body labels (outside title block region — ignored by title extractor)
        _make_label("R1", cx=0.18, cy=0.29),
        _make_label("R2", cx=0.68, cy=0.29),
    ]

    pipeline = PreprocessingPipeline(
        ocr_extractor=_mock_extractor(labels),
        cv_pipeline=_StubCV(),  # type: ignore[arg-type]
    )
    result = await pipeline.run(sample_electrical_image)

    # Structural checks
    assert isinstance(result, DiagramMetadata)
    assert result.source_filename == "sample_electrical.png"
    assert result.format == "png"
    assert result.width_px == 800
    assert result.height_px == 600

    # All OCR labels surfaced
    assert len(result.text_labels) == 5

    # Title block extracted from in-region labels
    assert result.title_block is not None
    assert result.title_block.drawing_id == "TEST-001"
    assert result.title_block.revision == "A"
    assert result.title_block.scale == "1:1"
    assert result.title_block.bbox is not None
